### ISSUE TITLE
CSS of shortcodes not loaded with twig, calling with markdown|shortcodes filter

### ISSUE THREAD

**Issue by zaszlo** [getgrav/grav-plugin-shortcode-core#100]
CSS of shortcodes not loaded with twig, calling with markdown|shortcodes filter, like so:

`{{ ('[ui-polaroid angle="-3" margin="30px 50px 20px 0" position="left" title="' ~ album.title ~ '"]![](' ~ album.img ~ ')[/ui-polaroid]') |markdown | shortcodes }}`

And if I start the twig by
```
{% block stylesheets %}
    {% do assets.addCss('plugin://shortcode-ui/css/ui-polaroid.css', 1) %}
{% endblock %}
{% extends 'partials/base.html.twig' %}
```
If the css is loaded as last one or first one, the polaroid renders fine on the page, but the whole page is screwed up. If I insert a ui-polaroid shortcode to the content section, the css is placed after the facebook plugin's css part and the page is rendered well, but I can't exactly say after/before which css to add this one, can I? 

How should I solve this?

**Comment by w00fz** [comment]
you need to call `{{ parent() }}` when you use block stylesheets, otherwise you are just overriding the whole block and it won't load anything else.

``` twig
{% extends 'partials/base.html.twig' %}
{% block stylesheets %}
    {% do assets.addCss('plugin://shortcode-ui/css/ui-polaroid.css', 1) %}
    {{ parent() }}
{% endblock %}
```

You can also swap the lines so `parent()` happens before your css, depending how you want this to load. Right now it will first load ui-polaroid and then everything else.
