### ISSUE TITLE
align-shortcodes breaks css styling

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-shortcode-core#29]
adding center/left/right shortcodes to a text breaks css styling.
text not rendered as paragraph anymore, only as element. paragraph css style gets lost.

**Comment by rhukster** [comment]
Example of final md with short codes  please.

**Comment by axel-rank** [comment]
I'm using the example of plugin docs

This is some [u]bb style underline[/u] and not much else

[center]This is centered[/center]

This is [size=30]bigger text[/size] and this is [color=blue]blue text[/color]

Size and underline shortcodes keeps my paragraph styling (font-size 1.2em, font-style italic).
When I use center/left/right shortcode paragraph styling gets lost:
![pstyle](https://cloud.githubusercontent.com/assets/12480617/22344005/a432b868-e3fa-11e6-9d4e-b3fecc4dee61.png)

**Comment by flaviocopes** [comment]
This is because the align shortcode wraps the line in a `div`.

`<div style="text-align: center;">This is centered</div>`

Wouldn't say this is a problem, just a design decision.

You can write your own plugin to render shortcodes in the way you want, see https://github.com/getgrav/grav-plugin-shortcode-core/#developing-shortcode-plugins
