### ISSUE TITLE
Disappearing twig_vars

### ISSUE THREAD

**Issue by OleVik** [getgrav/grav-plugin-shortcode-core#34]
With both the TwigFeeds-plugin and the Shortcode Core-plugin active, the latter is removing `twig_feeds` from `.twig_vars` when in the module-context. That is, `{{ dump(twig_feeds) }}` will return the active feeds on a modular page's template (eg. `modular.html.twig`), but not when used on a module's template (eg. `text.html.twig`).

For example, installing the Core (v1.1.17) + Admin (v1.2.14) package, TwigFeeds v2.0.3, and Shortcode Core v2.5.3, adding `{{ dump(grav.twig.twig_vars.twig_feeds) }}` to `user/themes/antimatter/templates7modular/text.html.twig` will return null in the Debugger with Shortcode Core enabled. With it disabled, however, feeds are returned as an array. In the parent-template it returns regardless.

X-ref: [TwigFeeds issue 4](https://github.com/OleVik/grav-plugin-twigfeeds/issues/4#issuecomment-282567747).

**Comment by rhukster** [comment]
Strange! I will check this out as I have a release planned for some bug fixes I found on Friday anyway.

**Comment by rhukster** [comment]
Ok, well i am trying to reproduce this and can't.  But that's mainly to the fact that I can never get at the `twig_vars` in modular or page context.  This is because you are only adding your `twig_feed` variable to Twig during the `onTwigSiteVariables` and not in the `onTwigPageVariables` event which fires earlier.

I quickly tested my hypothesis my amending the the subscribed events in your TwigFeeds plugin:

```
class TwigFeedsPlugin extends Plugin
{
	public static function getSubscribedEvents() {
		return [
			'onTwigPageVariables' => ['onTwigSiteVariables', 0],
                        'onTwigSiteVariables' => ['onTwigSiteVariables', 0]
		];
	}
...
```

Then it worked fine for me.  However, you should check to make sure the variable is not already there before you do all this processing work.  The situation is when cache is disabled, or cache is getting re-populated the work will be done twice, where it only needs to be done once.
