### ISSUE TITLE
Shortcode breaks Breadcrumbs

### ISSUE THREAD

**Issue by Crolug** [getgrav/grav-plugin-shortcode-core#40]
When Shortcode plugin is activated, Breadcrumbs plugin stops working, i.e. doesn't show any path.

**Comment by rhukster** [comment]
Can't replicate this.. I have shortcore-core plugin enabled, and i have breadcrumbs showing up.

**Comment by rhukster** [comment]
OK, this is fixed with this commit:

https://github.com/getgrav/grav-plugin-shortcode-core/commit/64e5e5fdc9080ece1d092960c8c557f44343857e

but needs this commit in Grav:

https://github.com/getgrav/grav/commit/9d8fc4a065f8c74f7062d2277255ff655a55970e

I've added this to both 1.5 and 1.6 branches so should be available shortly, but you can manually merge these commits if you need it fixed ASAP.
