### ISSUE TITLE
Sections are not cached

### ISSUE THREAD

**Issue by giansi** [getgrav/grav-plugin-shortcode-core#5]
When cache is enabled, sections are displayed only when the cache is built the first time.

**Comment by rhukster** [comment]
Are you running the latest version of Grav? Latest release is needed for this to work correctly as I had to add a new `contentMeta` caching mechanism.

**Comment by giansi** [comment]
Yes, it is. 

    You are already running the latest version of Grav (v1.0.10) released on Thu Feb 11 22:37:50 2016

**Comment by rhukster** [comment]
Is this a modular page?

**Comment by giansi** [comment]
Sorry no.

**Comment by giansi** [comment]
would you like I send you the whole project?

**Comment by rhukster** [comment]
Then i'll probably need to get a copy of your site in question.  

The reason I did the refactor with this new contentMeta stuff is to ensure that you can store this kind of data alongside the page in the cache. The previous mechanism was not reliable in all situations.  I was seeing odd siutations where things worked for some pages, and not others.  This has proved reliable in all my testing.

**Comment by giansi** [comment]
Let me know when I can send it to you

**Comment by rhukster** [comment]
just put it on drobox or something and paste the link here.

**Comment by giansi** [comment]
https://www.dropbox.com/s/r145zli0gi1l44u/gravstrap.tar.gz?dl=0

**Comment by giansi** [comment]
The shortcode is user/plugins/gravstrap/shortcodes/Bootstrap/JumbotronShortcode.php

**Comment by rhukster** [comment]
which page can i see this in action?

**Comment by giansi** [comment]
home

**Comment by rhukster** [comment]
Looks like your not doing it right.. compare to the new `section` shortcode:

```
    public function init()
    {
        $this->shortcode->getHandlers()->add('section', function(ShortcodeInterface $sc) {
            $name = $sc->getParameter('name');
            $object = new ShortcodeObject($name, $sc->getContent());
            $this->shortcode->addObject($sc->getName(), $object);
        });
    }
```

the `ShortCodeObject` contains a name and the content of the shortcode, then this is assigned to the manager via `addObject`

**Comment by giansi** [comment]
Sorry, I'm talking about assets here. I'm sharing another tar where I put you author section example and I changed the cache enabling to true in config settings.

**Comment by giansi** [comment]
https://www.dropbox.com/s/r145zli0gi1l44u/gravstrap.tar.gz?dl=0

**Comment by giansi** [comment]
Could you also check how I had to call the author shortcode. I had to call it {{ grav.shortcode.objects.section.author }} because {{ grav.shortcode.section.author }} does not work

**Comment by rhukster** [comment]
Well it's something on your end. 

First i fixed the reference to the section. You were doing `{{ grav.shortcode.objects.section.author }}` this is not correct.  What you are doing is getting the shortcode manger instance from Grav, then getting the objects instance directly, then getting the section and author.  While this works on first load, the shortcode manager is only in play when the content is processed, not on cached pages.  So understandably, it's not working on other pages.  

If you look in the shortcode-core plugin, you will see that `onPageInitialized` is loading the data for assets from `Page::contentMeta()`.  This is effectively loading it from the page cache.  Then these are added to the asset manager.  Objects are loaded from `contentMeta` in the Twig vars event, and adding them directly to a `shortcode` variable.  This is why you need to use `shortcode.section.author` syntax.

However, that alone was not fixing things. I stripped out all your gravstrap content and disabled the gravstrap plugin.  Then things started working.  So your doing something in gravstrap plugin that is breaking the logic of shortcode-core.  Because with this stripped out version things work fine.

I've attached the stripped out version so you can see section working even with cache on.

https://dl.dropboxusercontent.com/u/73693/gravstrap2.zip

**Comment by giansi** [comment]
Ok, I found the problem. Originally that page was modular and I forgot to remove the content parameter.
