### ISSUE TITLE
Shortcode-Core breaks Contact Us form on Land.io template

### ISSUE THREAD

**Issue by igkvl** [getgrav/grav-plugin-shortcode-core#58]
When Shortcode-Core plugin is activated, Contact Us form stops working, i.e. doesn't show any field on modular page.
 
Version of Grav (v1.5.6) released on Fri Dec 14 22:08:22 2018
Land.io skeleton from https://getgrav.org/download/skeletons/gateway-site/1.0.0
Ubuntu 18.04

**Comment by rhukster** [comment]
Is this a problem with "land.io" or "gateway" ??? You say one, and then link to the other.

**Comment by rhukster** [comment]
OK, this is fixed with this commit:

https://github.com/getgrav/grav-plugin-shortcode-core/commit/64e5e5fdc9080ece1d092960c8c557f44343857e

but needs this commit in Grav:

https://github.com/getgrav/grav/commit/9d8fc4a065f8c74f7062d2277255ff655a55970e

I've added this to both 1.5 and 1.6 branches so should be available shortly, but you can manually merge these commits if you need it fixed ASAP.
