### ISSUE TITLE
Shortcode core breaks Taxonomy List plugin

### ISSUE THREAD

**Issue by cir52** [getgrav/grav-plugin-shortcode-core#61]
When the Shortcode-Core plugin (v3.0.1) is activated, Taxonomy List plugin (v1.3.3) doesn't pull taxonomies anymore.

**Comment by rhukster** [comment]
OK, this is fixed with this commit:

https://github.com/getgrav/grav-plugin-shortcode-core/commit/64e5e5fdc9080ece1d092960c8c557f44343857e

but needs this commit in Grav:

https://github.com/getgrav/grav/commit/9d8fc4a065f8c74f7062d2277255ff655a55970e

I've added this to both 1.5 and 1.6 branches so should be available shortly, but you can manually merge these commits if you need it fixed ASAP.
