### ISSUE TITLE
onPluginsInitialized Commit --> prevents form messages processing

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-shortcode-core#65]
Your commit:

https://github.com/getgrav/grav-plugin-shortcode-core/commit/c76d7f7f89731569989100c27a4f2413c9b81ae4

![Bildschirmfoto_2019-03-19_21-09-00](https://user-images.githubusercontent.com/12480617/54638515-809a0d80-4a8b-11e9-9bb6-d582fe1fb73f.png)

prevents form messages processing. (in modular forms)

Changing back to value: 0  ---> everythings working again

**Comment by rhukster** [comment]
how about changing onPluginsInitialized in forms to 10?

**Comment by axel-rank** [comment]
Yes, working. But only if I set onPluginsInitialized in shortcode-core to 0.

**Comment by rhukster** [comment]
I cannot replicate this.. What is your setup? It's probably something specific to your Grav version and probably plugins installed.

Can you create a package for me where I can see this happening?

**Comment by rhukster** [comment]
Actually i am able to replicate... looking into it.

**Comment by rhukster** [comment]
OK, this is fixed with this commit:

https://github.com/getgrav/grav-plugin-shortcode-core/commit/64e5e5fdc9080ece1d092960c8c557f44343857e

but needs this commit in Grav:

https://github.com/getgrav/grav/commit/9d8fc4a065f8c74f7062d2277255ff655a55970e

I've added this to both 1.5 and 1.6 branches so should be available shortly, but you can manually merge these commits if you need it fixed ASAP.
