### ISSUE TITLE
Shortcodes are evaluated inside code blocks

### ISSUE THREAD

**Issue by N-Parsons** [getgrav/grav-plugin-shortcode-core#70]
Shortcodes are currently being evaluated inside of code blocks, where I would expect that the content should be included raw.

For example, I would expect a code block containing a shortcode to be formatted with the raw text, as it does here.

```
[fa=exclamation-circle /]
```

However, the actual result of the above code is to evaluate the shortcode and insert the Font Awesome icon into the code block.

![Exclamation-circle icon inside code block](https://user-images.githubusercontent.com/19746208/61787418-a81d3000-ae07-11e9-9871-e64b3a867aca.png)

This also happens with other shortcodes.

**Versions:**
- Grav: 1.6.11
- Shortcode-core: 4.1.2

**Comment by OleVik** [comment]
This is persistent across all shortcodes, and code blocks in Markdown Extra and Prism Highlight shortcodes behave the same way. Just to add to delineating a possible solution, escaping the code inside blocks is possible, but would this break copy-pasting code samples? If so, the shortcode-renderer should probably check for wrapping code blocks instead.

**Comment by rhukster** [comment]
There are basically two ways of processing a shortcode:

1. After markdown is processed
2. Before markdown is processed

These two approaches are important because, for the most part, shortcodes make more sense when they can 'wrap' markdown, so they process **after** markdown. 

For example a `[div][/div]` shortcode would be useless if it ran before markdown is processed because it would add the relevant HTML `<div></div>` tags, and then the markdown parser would promptly **skip** all markdown processing between those divs because it won't process markdown **inside** HTML. So this shortcode and most others run after markdown processing has already occurred using this approach:

```php
$this->shortcode->getHandlers()->add('div', function(ShortcodeInterface $sc) { ... }
```
Notice the `getHandlers()` call is the standard way to add a handler.

However, there are situations when you need to process the shortcode **before** the markdown processing to ensure markdown **is skipped**, like in the example of a code block. This is why in the [Prism Highlighter](https://github.com/trilbymedia/grav-plugin-prism-highlight) plugin, we use this approach to defining the shortcode:

```php
$this->shortcode->getRawHandlers()->add('prism', function(ProcessedShortcode $sc) { ... }
```

The difference here is it uses `getRawHandlers()` to ensure the handler is processed to the content in the _raw_ state.

BTW, i've added this information to the README.md

**Comment by N-Parsons** [comment]
Thanks for the implementation details.

While it goes against what I would expect of the behaviour, having thought about it a bit more and read the README in more detail, I actually think that the current behaviour is probably the most useful.

The easy solution for what I wanted is to add `[raw][/raw]` shortcodes inside the markdown code fences. It still feels a bit clunky having to do 2 things, so I'm considering creating a shortcode that provides code block functionality with optional raw processing. I need to have a think about the best default behaviour and nomenclature though.

**Comment by rhukster** [comment]
the `[raw][/raw]` tag is the correct solution, it basically turns off shortcode handling between those tags.
