### ISSUE TITLE
[Bug] Missing Font Awesome Icons

### ISSUE THREAD

**Issue by CyberneticCody** [getgrav/grav-plugin-shortcode-core#81]
Hello! I recently discovered the FontAwesome support that came with Grav and this and have begun using it. However, when trying to use icons, some do not show up. When loading the page there are no errors logged in the console or network traffic.
I am using Grav 1.6.19, Admin 1.9.12, and Shortcode Core 4.1.7

I have tried using FA 5 by selecting enable in the plugin settings, but it does not make a difference. As can be seen in the image below I also tried adding options to make the icon appear (See the PHP icon)
'
Any help with this would be great, thank you!

![font awesome issue](https://user-images.githubusercontent.com/55600371/71987079-85d36f00-31fb-11ea-9d6a-d1449140bb08.PNG)
![font awesome issue 2](https://user-images.githubusercontent.com/55600371/71987118-9552b800-31fb-11ea-8252-a88788489ce3.PNG)

**Comment by LivingWithHippos** [comment]
I have the same issue. Some of them do not work, I noticed mainly the ones with two words in the name with "-" in the middle, but it may be a coincidence.

**Comment by N-Parsons** [comment]
Hi @CyberneticCody and @LivingWithHippos,

There's some extra spacing between icons where the missing ones should be, which suggests that you aren't loading a version of Font Awesome that has those icons. The toggle switch just enables FA5 compatibility in this plugin, rather than loading FA5 for you, so you will need to load it yourself.

If you want to use these icons, check out the [Font Awesome site](https://fontawesome.com/start) to learn how to add Font Awesome to your project.

**Comment by CyberneticCody** [comment]
Ahh, makes sense. Thank you!
